services:
  db:
    image: postgres:17
    container_name: sazon_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sazon
      POSTGRES_PASSWORD: sazon_password
      POSTGRES_DB: sazon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
